### ISSUE TITLE
pdfを開くための方法調査

### ISSUE THREAD

**Issue by shunya9811** [ChubachiPT2024/manakan#104]
### 何をやるのか
manakanにて、学生の提出物(pdfファイル限定)を表示するための、ライブラリ等の検討

### なぜやるのか(目的)
manakanに導入するにあたって、最適なライブラリを選びたい

## 完成の定義

実現できるライブラリを列挙した上で、実現可能性からライブラリの順位付けを行う

**Comment by rt4716** [comment]
こんな感じですか?
react-pdf を試してうまくいかなかったら、react-pdf-viewer っていうのがいいんですかね...?

|実装|pros/cons|備考|
|---------------|---------------|---------------|
|[react-pdf](https://github.com/wojtekmaj/react-pdf)|o:Reactコンポーネント<br>o:互換性が高い<br>x:複雑な事はできない(?)||
|[pdfjs-dist](https://www.npmjs.com/package/pdfjs-dist)|o:いろいろチューニングできそう<br>x:react-pdfよりは設定とかいりそう|[github](https://github.com/mozilla/pdf.js)|
|[react-pdf-viewer](https://react-pdf-viewer.dev/)|o:Reactコンポーネント<br>o:プラグインでカスタマイズができる<br>x:プラグインとか使ったら比較的設定がいりそう<br>x:比較的重そう(?)||

**Comment by cozy07** [comment]
[react-pdf-viewer](https://react-pdf-viewer.dev/) ライセンスを見てると有料っぽく見えているので、選択肢からは外れそうな気がしてます！

**Comment by shunya9811** [comment]
そしたら次のスプリントあたりで、react-pdf試してみて、だめだったらpdfjs-distを試してみるのが良さそうですね
