### ISSUE TITLE
ReviewページのPDF表示

### ISSUE THREAD

**Issue by cozy07** [ChubachiPT2024/manakan#112]
## 概要
Reviewページ内で提出物のPDF (複数) を学生毎に表示する。

### 何をやるのか
- PDF 表示部のモジュール化
- react-pdf による PDF の表示
- API 経由でのデータ取得

### なぜやるのか(目的)
- 評価、比較のページでのファイルビューワを実装する為

**Comment by shunya9811** [comment]
@a2311kk @rt4716 
結局PDFはどちら側で開くことにしますか？
それによっては、ここでの作業が、後回しになるかもですね

**Comment by rt4716** [comment]
7/10 の meeting の話だと、一旦クイックな方法で実装した後、後々余裕があればリファクタリングするという結論になっていたかとおもいます。

今回だと、reviewPage 側がファイルパスを貰って表示のかなとおもっていましたが、如何でしょう。

**Comment by rt4716** [comment]
一旦、
- PdfView.tsx にモジュール化
- サンプルファイルを /public/ 以下に配置して HTTP GET で取得、その後 Uint8Array としてレンダリング
する形で実装しています。

ちょっと UseEffect 地獄にはまっていて、ChatGPT さんにがんばってもらって UseMemo() やら UseCallback やらを使って Warning の抑制を試みていますが、まだ、下記の Warning はでます。

とりあえず、描画はできているようなのですが...

```
react-pdf.js?v=b6092ff6:41 Warning: File prop passed to <Document /> changed, but it's equal to previous one. This might result in unnecessary reloads. Consider memoizing the value passed to "file" prop.
```

**Comment by rt4716** [comment]
残タスク: 
- テストファイルから API 経由での取得への変更

**Comment by rt4716** [comment]
conflict をマージする際に、一旦このブランチを hard push した為、過去のものを pull してる方がいたら、一旦削除して pull 仕直しをおねがいします。

**Comment by rt4716** [comment]
https://github.com/ChubachiPT2024/manakan/blob/7de6cd3919efbc9b944c2ac55c1684fd22746b50/src/presentation/pages/Review.tsx#L25-L31

で location.state から受けとった reportId, studentNumIds を元に getSubmissionSummariesAsync を読んだところ、
"The report is not found" がでちゃう。。。

console.log でみると reportId はよさそうなんですけどね。。。

![image](https://github.com/user-attachments/assets/f33c83bf-8581-4f21-b660-c34b14392450)

**Comment by shunya9811** [comment]
```
export class SubmissionSummariesGetCommand {
  /**
   * コンストラクタ
   *
   * @param reportId レポート ID
   * @param studentNumIds 学籍番号リスト
   */
  public constructor(
    public readonly reportId: number,
    public readonly studentNumIds: number[]
  ) {}
}
```
studentNumIdsはnumberで学籍番号なので、a2340sw等のほうではなく、8桁の23745140になってもらわないと取得できないんですよね
なので分類ページの方で、numIdに変更しないといけないですね

**Comment by shunya9811** [comment]
@rt4716 
>なので分類ページの方で、numIdに変更しないといけないですね

こちらの変更が、Classificationページでのデータ書き込みの実装 #138 
ここで行われているみたいですね

**Comment by rt4716** [comment]
なんとか
- Review.tsx: SubmissionSummariesGetCommand
- PdfView.tsx: getSubmissionFileAsync
を使ってAPI経由のデータ呼び出しには成功したのですが、どうもPDF表示がまっしろけで、できない。



![Image](https://github.com/user-attachments/assets/67f57898-c291-4ac8-9ec2-e87a64316464)



とおもったら、

react-pdf の実験につかったアプリでも一緒でした。


![Image](https://github.com/user-attachments/assets/e92dfba7-8f70-4582-937f-26a9eae2a354)

どうもここらへんのエラーと向き合わないといけないっぽいです。

```
Warning: loadFont - translateFont failed: "UnknownErrorException: The CMap "baseUrl" parameter must be specified, ensure that the "cMapUrl" and "cMapPacked" API parameters are provided.".
pdf.worker.min.mjs:21 Warning: loadFont - translateFont failed: "UnknownErrorException: The CMap "baseUrl" parameter must be specified, ensure that the "cMapUrl" and "cMapPacked" API parameters are provided.".
2react-pdf.js?v=df146007:547 Warning: Error during font loading: The CMap "baseUrl" parameter must be specified, ensure that the "cMapUrl" and "cMapPacked" API parameters are provided.
```

**Comment by shunya9811** [comment]
SubmissionSummariesGetCommandから取得したもので、さらに、SubmissionFilegetcommandを呼び出す想定を木村さんは、されてるんじゃないですかね
