### ISSUE TITLE
Classificationページでのデータ取得

### ISSUE THREAD

**Issue by cozy07** [ChubachiPT2024/manakan#113]
### 何をやるのか
classificationpageでAPIからデータを取得する

### なぜやるのか(目的)
classificationpageでデータを表示するため

**Comment by shunya9811** [comment]
@a2311kk 
今すぐには、必要はないかもですが、reviewページ用にgetSubmissionSummaryを作成することに決まったので、
src/application/reportLists/reportListData.tsの
```
public constructor(
    public readonly courseId: number,
    public readonly courseName: string,
    public readonly reportId: number,
    public readonly reportTitle: string,
    public readonly items: ReportListItemData[]
  ) {}
```
reportListItemDataは修正することになるんですかね？


益田さん、小澤さんのために言っておくと
ここでのissueでは、とくにReportListItemData[]は使わないと思うので、気にせず実装してもらって構わないです。

**Comment by shunya9811** [comment]
@a2307yo @tadashimasuda 
https://github.com/ChubachiPT2024/manakan/pull/108
ここでのコードが参考になるかもしれないです。

**Comment by shunya9811** [comment]
評価ページのルーティングを変えたので、
/src/presentation/import/components/DropForm.tsx
におけるルーティング処理も変えてもらいたいです。
```
navigate(`/evaluation/${reportId}`);
```
