### ISSUE TITLE
Classificationページでのデータ書き込み

### ISSUE THREAD

**Issue by cozy07** [ChubachiPT2024/manakan#114]

**Comment by shunya9811** [comment]
このissueでは、src/application/assessments/assessmentClassifyCommand.tsでのオブジェクトを作成して、src/preload.tsの
classifyAssessmentAsync関数を使って、書き込むイメージですかね。

**Comment by a2307yo** [comment]
@tadashimasuda  @tadashimasuda 
サポートありがとうございました
