### ISSUE TITLE
0評点の順位付けを削除する

### ISSUE THREAD

**Issue by cozy07** [ChubachiPT2024/manakan#133]

**Comment by a2307yo** [comment]
下記のブランチで実装開始
[feature/delete_0grade_rank](https://github.com/ChubachiPT2024/manakan/tree/feature/delete_0grade_rank)

**Comment by a2307yo** [comment]
画面上で下記の内容を確認した
・grade０のrankが5段階ではなくなっていること
・grade０にReportが割り当てられること
・grade０に割り当てたレポートが画面をリロードしても割り当たっていること
