### ISSUE TITLE
React-PDF 導入後、Windows で npm start (electron-forge start) に失敗する

### ISSUE THREAD

**Issue by a2311kk** [ChubachiPT2024/manakan#152]
# バグの説明

React-PDF 導入後、Windows で npm start (electron-forge start) に失敗する

## バグの再現手順

# 期待される動作

# スクリーンショット

# 追加のコンテキスト

**Comment by a2307yo** [comment]
私も「とりあえず何とかする方法」でelectron-forge start が成功しました！
