### ISSUE TITLE
npm run make で生成した manakan.exe を実行し、Review ページを開くと /pdf.worker.min.mjs  が見つからないエラーが発生する

### ISSUE THREAD

**Issue by a2311kk** [ChubachiPT2024/manakan#168]
# バグの説明

## バグの再現手順

環境: Windows

![Image](https://github.com/user-attachments/assets/444e485d-e1d5-45d5-baa2-97a78977c756)

# 期待される動作

# スクリーンショット

# 追加のコンテキスト

**Comment by rt4716** [comment]
下記PRで対処(したつもり)。
https://github.com/ChubachiPT2024/manakan/pull/171

特に Windows 環境の方、
- branch を pull する
- pull した branch で npm run make
- 生成されたパッケージ (windows なら .exe, macOS なら .app) を実行し、テストデータでPDFを表示させる
テストをお願いできますでしょうか。

一応、自分のローカル環境 (macOS) では直ったようにみえる
