### ISSUE TITLE
【Review ページ】分類、メモ、フィードバックを更新するたびに、1 番目の学生が選択される

### ISSUE THREAD

**Issue by a2311kk** [ChubachiPT2024/manakan#209]
# バグの説明

## バグの再現手順

1. Classification ページで 2 人以上の学生を選択する
2. Review ページを開く
3. 2 番目以降の学生を選択する
4. 分類、メモ、フィードバックのいずれかを変更し、フォーカスを外す

# 期待される動作

# スクリーンショット

# 追加のコンテキスト

#208 の対応によって発生したものと思われます。

**Comment by shunya9811** [comment]
確かに考えてみたら、更新されて、一番目の学生に戻ってしまいますね、、、
