### ISSUE TITLE
ToBe 情報モデル図（クラス図）の作成

### ISSUE THREAD

**Issue by shunya9811** [ChubachiPT2024/manakan#25]
レビュアー：@cozy07

**Comment by a2307yo** [comment]
下記のファイルに作成した
https://drive.google.com/file/d/1S3Y9NJR5tntGv-KOgktk8JPtd7Qbc97M/view?usp=drive_link

**Comment by a2307yo** [comment]
manakan_UMLモデリングのモデルシートに情報モデル図を作成した

**Comment by shunya9811** [comment]
@a2307yo 情報モデル図のリファクタリングとして、再度SBIを作成してもいいのかなとおもったのですが、どうでしょう？もしよろしければ、私の方で作成します

**Comment by a2307yo** [comment]
再度SBIを作成をお願いします
