### ISSUE TITLE
技術調査

### ISSUE THREAD

**Issue by shunya9811** [ChubachiPT2024/manakan#28]
## 概要

開発に進んでいくため、技術選定を行う

### 何をやるのか
機能要件で挙げた以下の実現可能性を調べる
- フォルダーのインポート機能
- ファイルビューアー機能
- ドラッグ＆ドロップ操作
- ファイル書き込み機能
- 自動保存機能
- ローカルデータ保存機能（開いていたファイルや設定の保存）
- クロスプラットフォーム対応
- パッケージ化
- 開発環境構築の容易性
- 無償か、有償か
- 学習コスト

### なぜやるのか(目的)
開発環境の構築を行うため

## タスク(Sprint Backlog Item)

- [x] #33 
- [x] #34 
- [x] #35 
- [x] #36 

## その他

notionの技術調査ページ
https://www.notion.so/f992d0c2c0cb4a8c86c156741730a633

**Comment by cozy07** [comment]
言語で担当を分けたいと思いますので、以下分担でお願いします！

- Python @a2307yo 
- JavaScript @shunya9811 
- C# @a2311kk 
- Rust, Dart @rt4716

**Comment by shunya9811** [comment]
それぞれSBIを作っても、いいですかね？
