### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by shunya9811** [ChubachiPT2024/manakan#37]
### 何をやるのか
メンバーがElectronの開発を行っていけるように、環境を整える

### なぜやるのか(目的)
プロダクトを作成していくため

## タスク(Sprint Backlog Item)

- [x] #39 
- [x] #38 
- [x] #44 
- [x] #46 
- [x] #47 
- [x] #48 
- [x] #49 
- [x] #50 
- [x] #51 
- [x] #63 
- [x] #64 
- [x] #66
- [x] #69 
- [x]  #81

**Comment by a2307yo** [comment]
タスク(Sprint Backlog Item)がすべてクローズしているため、当PBIはクローズします。
またタスクが追加になって必要になったらリオープンしましょう。
