### ISSUE TITLE
画面のたたき台を作成する

### ISSUE THREAD

**Issue by a2307yo** [ChubachiPT2024/manakan#42]
## 概要
manakanの画面についてたたき台をFigmaで作成する

### 何をやるのか
1. 文面で必要な画面と画面でできることの洗い出し
1. 1に対して話し、画面の数と画面でできることを決定する
1. 一つずつ画面を作る。作る中でコンポーネント化できそうなパーツがあれば積極的に進める。
1. プロトタイプ化しFigma上でボタン押すとページ遷移する機能をつける

### なぜやるのか(目的)
画面のたたき台を作成し、それを基に開発チーム、プロダクトオーナと議論しmanakanの画面仕様を明確にする

## 完成の定義
全画面が存在するたたき台を作成し、Figmaのプロトタイプ機能でデモを行う

**Comment by tadashimasuda** [comment]
画面洗い出し
---
- ページ名
　動作
　動作→動作後
---
- Homeページ
	インポートフォームzdrug&drop)　→　ファイル名表示
	中間保存データから再開ボタン　→　確認モーダル

- 提出物全表示ページ
　　提出物一覧
　　提出物選択　→　提出物個別表示モーダル
	　メモ入力
	　フィードバック入力
	　分類
	相対評価へボタン → 分類できていなかったら警告
	保存済み表示（自動保存）

- 相対評価ページ（カンバンページ？）
	カンバン表示
	順位付け
	提出物個別表示モーダル
		メモ入力
		フィードバック入力
		分類
	保存済み表示（自動保存）
	エクスポートボタン → 確認モーダル

**Comment by tadashimasuda** [comment]
UIについての提案
---
TailWindテンプレートを使う
- 細かいCSSを書かなくていい
- 一定程度のクオリティが担保できる
- UIの統一感が出せる
- テンプレートにプラスでCSSを当てられるので 

Figmaにパーツのコンポーネントサンプルがあるので、これらを組み合わせる（コンポーネントパーツを作りたい場合は、参考に作成する）。私としては一定程度のクオリティが担保できることが一番のメリット

パーツ
https://www.figma.com/design/Hqx9tTZ1PDpfk8Q0drOizM/Tailwind-UI-Components-for-Figma-%7C-TailGrids-(Community)?node-id=102-227&t=cUH8BKrXtiYYcVbz-1

Tailwindを使用したデザインページ
https://tailwindui.com/templates?ref=sidebar

**Comment by a2307yo** [comment]
> ## UIについての提案
> 
> TailWindテンプレートを使う
> 
>     * 細かいCSSを書かなくていい
> 
>     * 一定程度のクオリティが担保できる
> 
>     * UIの統一感が出せる
> 
>     * テンプレートにプラスでCSSを当てられるので
> 
> 
> Figmaにパーツのコンポーネントサンプルがあるので、これらを組み合わせる（コンポーネントパーツを作りたい場合は、参考に作成する）。私としては一定程度のクオリティが担保できることが一番のメリット
> 
> パーツ https://www.figma.com/design/Hqx9tTZ1PDpfk8Q0drOizM/Tailwind-UI-Components-for-Figma-%7C-TailGrids-(Community)?node-id=102-227&t=cUH8BKrXtiYYcVbz-1
> 
> Tailwindを使用したデザインページ https://tailwindui.com/templates?ref=sidebar

統一感のあるデザインにできるのはいいですね！
私も少し調べてみました。
もし、アイコンを使うならMaterial Design Iconsを使いたいです

https://www.figma.com/community/file/1014241558898418245

**Comment by a2307yo** [comment]
私の作業分を共有いただいたプロジェクトにコピーしました

**Comment by tadashimasuda** [comment]
私の本のスキャナーのデスクトップアプリです。PDF扱うので参考になるかもです

![Image](https://github.com/ChubachiPT2024/manakan/assets/51233312/27b50ec2-f3c4-47ea-a81d-bd7236e63eff)
