### ISSUE TITLE
小澤さんの環境構築

### ISSUE THREAD

**Issue by shunya9811** [ChubachiPT2024/manakan#49]

**Comment by a2307yo** [comment]
### fnmの設定について
powershellのプロファイルは初期設定されているパスにファイルを作成することで解決した。
ドキュメントのパスが初期でOneDrive・・・のパスに割り当たっていることが問題だと思うが他への影響も考慮して
ドキュメントのパスは変更しないこととした

**Comment by a2307yo** [comment]
少し調べてみたがVoltaというバージョン管理ツールもよさそう。ただVoltaはWindowsの開発モードを有効にしないといけない。
プロファイルの変更とWindowsの変更、どちらにしてもひと手間かかるのは変わらないみたい。。。
