### ISSUE TITLE
高嶋さんの環境構築

### ISSUE THREAD

**Issue by shunya9811** [ChubachiPT2024/manakan#50]

**Comment by rt4716** [comment]
- 6/14 10pm 時点でやったこと
  -  macOS brew での node.js 環境の構築
  - チュートリアルのローカルパッケージ構築迄
  - JavaScript というか web front 全般にさっぱり知識がないのでやり初めたこと
    - Udemy 
      - https://www.udemy.com/course/nodejs-comp-guide/
      - これ見始めたけどそもそも JavaScript からという気もしてきた

**Comment by rt4716** [comment]
node LTS に変更する為にしたこと

とりあえず、
```brew install node@20```
して、shell に
```
# node LTS
PATH="/opt/homebrew/opt/node@20/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/node@20/lib"
export CPPFLAGS="-I/opt/homebrew/opt/node@20/include"
```
して、結果
```
yonayona:~$ node -v
v20.14.0
yonayona:~$ npm -v
10.7.0
```

**Comment by rt4716** [comment]
6/16 の日記
- 環境
  - どうやら volta がいいのか? みたいな事を考えて、
```
brew install volta
volta install node@lts
```
した
- 学習
  - 会社の Udemy で Node.js 系続き
    - JavaScript 全般 (arrow function, callback function, DOM とかそういう今時の全般...)
    - Node.js, npm 等全般 (ようやく package.json の位置付けと npm のローカルパッケージングがわかってきたとこ...)
  - 明日やること
    - とりあえず、Udemy のはここがキリがいいので React の学習に切り替える

**Comment by rt4716** [comment]
6/17 の日記
- 学習
  - Udemy で [モダンJavaScriptの基礎から始める挫折しないためのReact入門](https://www.udemy.com/course/modern_javascipt_react_beginner/?utm_source=adwords&utm_medium=udemyads&utm_campaign=LongTail_la.JA_cc.JP&campaigntype=Search&portfolio=Japan&language=JP&product=Course&test=&audience=DSA&topic=&priority=&utm_content=deal4584&utm_term=_._ag_107181210924_._ad_452531407122_._kw__._de_c_._dm__._pl__._ti_dsa-930814701079_._li_1009310_._pd__._&matchtype=&gad_source=1&gclid=Cj0KCQjwvb-zBhCmARIsAAfUI2sMeK-3WQMB46TGo0qD3tX035iARo5DFm_aWUZWD3Q9_fLDRc2fo-0aAq2rEALw_wcB&couponCode=JPLETSLEARNNOW) に手をつけてみた
    - 一旦、JavaScript で ToDo アプリのサンプみたいの組むのをやった
    - React のサワリに入ったところ位で時間切れ
  - 今のところ、こんな感じ。
    - やった
      - Node.js の仕組み (npm とかローカルパッケージとか)
      - 最近の JavaScript であそんでみる
    - やっている
      - React の仕組み (基本的なところ、TypeScript 抜き)
    - これから
      - React で遊んでみる
      - React + TypeScript で遊んでみる
      - React + TypeScript + Electron で遊んでみる (ゴール)
  - 迂遠な様ではあるが、そもそも知らんのが多すぎるのでステップ踏むのが結果早そう。
