### ISSUE TITLE
塚本さんの環境構築

### ISSUE THREAD

**Issue by shunya9811** [ChubachiPT2024/manakan#51]

**Comment by cozy07** [comment]
- [x] Electron クイックスタート
- [x] Electron チュートリアル
- [x] [Electron入門 ~ Webの技術でつくるデスクトップアプリ](https://zenn.dev/sprout2000/books/6f6a0bf2fd301c/viewer/13263)
とりあえず、Electronの仕組み（メインプロセス、レンダラープロセス）について理解しようと思い実施

- [electron-api-demos](https://github.com/electron/electron-api-demos)
- [jupyterlab](https://github.com/jupyterlab/jupyterlab)
- [vscode](https://github.com/microsoft/vscode)
のあたりでディレクトリ構成やテスト内容を眺めているが、まだ理解は浅い

**Comment by cozy07** [comment]
## VSCode設定周りの調査
Electron（React + Typescript）で作られているOSSリポジトリを参考にしてみる。
[wexond/browser-base](https://github.com/wexond/browser-base/blob/master/.vscode/settings.json)
[microsoft/vscode](https://github.com/microsoft/vscode/blob/main/.vscode/settings.json)
[GitHub desktop/desktop](https://github.com/desktop/desktop/blob/development/.vscode/settings.json)
### 結論
GitGubのsetting.jsonが使いやすそう
### 理由
簡潔な内容で理解しやすくて、最低限Typescriptで開発するための設定が入っている。

- TypeScriptのコンパイラ(tsdk)のパスを指定。
=> package.jsonで実行されるTypeScriptのバージョンは揃えることは揃えることは出来るが、tsdkを使うことでVSCodeの編集機能（インテリセンス、型チェック、コード補完など）でもプロジェクト内のTypeScriptのバージョンが使用されるようになる。
- 検索対象から特定のフォルダ(dist, node_modules, outなど)を除外。
- ファイルエクスプローラーで表示しないフォルダ(git, svn, hg, DS_Store, node_modules, dist, outなど)を指定。
- ファイルの末尾に改行を挿入。
- タブのサイズを2に設定。
- Prettierの設定：
    - セミコロンを付けない
    - シングルクォートを使用
    - 末尾のカンマをES5の仕様に従って付ける
- ファイル保存時に自動でフォーマットを実行。
- Prettierが無視するファイルを.prettierignoreファイルで指定。
- ESLintの設定：
    - 設定ファイルのパスを.eslintrc.ymlに指定
    - カスタムルールのパスをeslint-rulesに指定
- ESLintでバリデーションする言語(JavaScript, JSX, TypeScript, TSX)を指定。
- デフォルトのフォーマッタをPrettierに設定。
