### ISSUE TITLE
インメモリ Repository とプロセス間通信の実装

### ISSUE THREAD

**Issue by a2311kk** [ChubachiPT2024/manakan#89]
### 何をやるのか

永続化処理を実装する。

### なぜやるのか(目的)

各機能に共通して必要となる基盤を実装し、各機能を実装できるようにするため。

## 完成の定義

永続化処理の実装完了。

**Comment by shunya9811** [comment]
データの保存先については、どう考えてますかね？JSONで保存するのと、SQLiteを使って行くのとあると思うんですけど
