### ISSUE TITLE
画面の実装: ClassificationPage

### ISSUE THREAD

**Issue by rt4716** [ChubachiPT2024/manakan#97]
## 概要
画面の実装: Home

**Comment by tadashimasuda** [comment]
コンポーネントの全体像
- sidemenu
    -  header title
    - no-classification-board
    - export button

- wrapper
    - corse-title
    - buttons
        - open-button
        - cancel-button
    - classified-boards
        - classified-board
            - header
            - rank-row
                - card
           
予定する工程
- sidemenu
    - UI
    - dndで必要なfunc定義
- wrapper,corse-title,buttons
    - UI
    - usestateでbuttonのオンオフ
- classified-boards
    - UI
    - dndで必要なfunc定義

**Comment by tadashimasuda** [comment]
https://ja.react.dev/reference/react/useState
