### ISSUE TITLE
画面の実装:ReviewPage

### ISSUE THREAD

**Issue by rt4716** [ChubachiPT2024/manakan#98]
## 概要
画面の実装: ReportPage

### 何をやるのか
- [x] レビューページへのリンク
- [x] pdfブロック
- [x] 学生を切り替えるラジオボタン
- [x] 提出者情報
- [x] 分類のボタン
- [x] 点数表示
- [x] メモ記入欄
- [x] フィードバック記入欄
- [x] その他調整

### なぜやるのか(目的)
レポートページにおけるUIを作成して、各機能を作成する土台を作る

## 完成の定義

「何をやるのか」のチェックがすべてつく

## その他

![Image](https://github.com/ChubachiPT2024/manakan/assets/64852663/7e53aa1e-b620-486b-929a-9b359a696f5b)

**Comment by shunya9811** [comment]
レポートページって名前を

**Comment by shunya9811** [comment]
ReportPageからReviewPageへと変更しました

**Comment by shunya9811** [comment]
# 残りやること
- PDF表示部分のサイズを大きくする
- 学生選択のラジオボタンをMUI
- サイドバーの部品のサイズ拡大
- 戻るボタン
