### ISSUE TITLE
画面の再設計: ReportPage

### ISSUE THREAD

**Issue by rt4716** [ChubachiPT2024/manakan#99]
## 概要
画面の再設計: ReportPage

### 何をやるのか
現状のFigma画面を更新
- Report画面
- Home画面

### なぜやるのか(目的)
土曜の画面構築の材料にする

**Comment by tadashimasuda** [comment]
【前提】
現在の大きめカードは廃止、小さめのカードにするのは確定な気がするので小さめで作成しています。
レポートページで複数見れることを考えるとチェックボックスは必須だと思います。
ざっくりな方針の共有なので、細かいスタイルは調整していません。
より使いやすいUIを考えるときりがないので、使いにくい状況は避けている＆＆開発コストが高すぎないことを想定で作成しています。
【内容】
マトリックス案
HomeMatrix1（https://www.figma.com/design/xbLZGfMMMhzcNr9OdFifme/manakan?node-id=174-1042&t=DpHSvZlknLqDl7dn-1）
		縦横を完全分離し、より分かりやすい仕様。デメリットとしては、列の高さが誰つに影響がでてしまうことです。
HomeMatrix2（https://www.figma.com/design/xbLZGfMMMhzcNr9OdFifme/manakan?node-id=182-1251&t=DpHSvZlknLqDl7dn-1）
		現在の分類ボードの中でセグメントを背景色で切り分けています。
HomeMatrix3（https://www.figma.com/design/xbLZGfMMMhzcNr9OdFifme/manakan?node-id=183-1518&t=DpHSvZlknLqDl7dn-1）
		HomeMatrix2を線で区切ったverです。海外のスーパーのレジの区切り棒のイメージです。
レポートページ（https://www.figma.com/design/xbLZGfMMMhzcNr9OdFifme/manakan?node-id=176-3004&t=DpHSvZlknLqDl7dn-1）
数人のレポートが一画面で見れることが必須なので、サイドメニューに入力フォームを設け、その中で入力先を切り替えるイメージです。
フォルダ内のファイルの切り替えについては、そこまで重要ではないので全てのファイルを連結した状態を想定しています
